#!/bin/bash
find . -mindepth 1 -type d -not -path '*/\.*' | { read first_line; echo "$(( $(echo "$first_line" | wc -l) - 2 )) directories, $(( $(find . -type d | wc -l) - $(echo "$first_line" | wc -l) )) subdirectories"; }
